[package]
name = "usvg-remote-resolvers"
version = "0.1.0"
edition = "2021"
authors = ["aobatact"]
rust-version = "1.67.1"
description = "A library for resolving remote resources in SVG files for usvg."
repository = "https://github.com/aobatact/usvg-remote-resolvers"
license = "MIT"
keywords = ["svg"]

[dependencies]
reqwest = { version = "0.12.9", default-features = false, optional = true }
tokio = { version = "1.41.1", default-features = false, optional = true, features = ["rt", "rt-multi-thread"] }
usvg = "0.44.0"

[dev-dependencies]
mockito = "1.6.1"
resvg = "0.44.0"
tokio = {version = "1.41.1", features = ["macros"] }

[features]
default = ["reqwest_blocking"]
reqwest = ["dep:reqwest", "dep:tokio"]
reqwest_blocking = ["dep:reqwest", "reqwest/blocking"]
